-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mailing_archive_stat`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_mailing_archive_stat
-- *
-- * Mailing Archive Statistics
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailing_archive_stat` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingArchiveStat ID',
  `mailing_id` int unsigned COMMENT 'FK to Mailing',
  `recipients` int unsigned COMMENT 'Number of recipients',
  `deliveries` int unsigned COMMENT 'Number of emails delivered',
  `opens` int unsigned COMMENT 'Number of emails opened',
  `clicks` int unsigned COMMENT 'Number of links clicked',
  `forwards` int unsigned COMMENT 'Number of mails forwarded',
  `replies` int unsigned COMMENT 'Number of replies',
  `bounces` int unsigned COMMENT 'Number of bounces',
  `unsubscribes` int unsigned COMMENT 'Number of unsubscribes',
  `optouts` int unsigned COMMENT 'Number of optouts',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_mailing_archive_stat_mailing_id FOREIGN KEY (`mailing_id`) REFERENCES `civicrm_mailing`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
